CREATE TABLE "user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "phone" varchar(11) UNIQUE NOT NULL,
  "password" varchar(100) NOT NULL,
  "email" varchar(50) UNIQUE NOT NULL,
  "user_type_id" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT 'now()',
  "updated_at" timestamp NOT NULL DEFAULT 'now()'
);